### ISSUE TITLE
META.* files do not contain PDL

### ISSUE THREAD

**Issue by eserte** [PDLPorters/pdl-graphics-plplot#5]
META.yml and META.json currently do not list PDL as a prerequisite. Probably this depends whether PDL is already installed on the machine creating the PDL-Graphics-PLplot distribution (see https://github.com/PDLPorters/pdl-graphics-plplot/blob/master/Makefile.PL#L20-L27 ). 

This means that the metacpan page does not list PDL as a dependency, and also PDL-Graphics-PLPlot is not listed as a reverse dependency. Also, test reports do not list PDL (and the installed version) as a dependency (for example http://www.cpantesters.org/cpan/report/664e55ae-287e-11ea-8a52-45591f24ea8f ), which means full statistical analysis in case of failures are not possible.

**Comment by mohawk2** [comment]
Thanks for these reports!
