### ISSUE TITLE
PDL-Graphics-PLplot-0.74 not yet pushed to GitHub

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl-graphics-plplot#7]
cc: @doughunt

I noticed that [PDL-Graphics-PLplot-0.74](https://metacpan.org/release/DHUNT/PDL-Graphics-PLplot-0.74) has not been pushed to GitHub yet. Could you push those commits please when you get a chance?

@mohawk2, if I'm looking at the settings correctly, I think @doughunt needs commit bits.

**Comment by mohawk2** [comment]
@doughust I've invited you to be a collaborator. Please push to this repo your commits and a tag for the release you've put on CPAN :-)

**Comment by doughunt** [comment]
Hi all:  I tried to respond to the invitation sent by @mohawk2 to get a 
commit bit for the github repo.  Got a 404 error on github.

Could someone send this invitation again?

Regards,

   Doug Hunt

**Comment by zmughal** [comment]
Hi @doughunt, I'll try to e-mail you the link to try again. I think that the link only works if logged in.

**Comment by zmughal** [comment]
Closing, fixed by <https://github.com/PDLPorters/pdl-graphics-plplot/pull/8>. Thank you, @doughunt!

Changes are tagged at [0.74](https://github.com/PDLPorters/pdl-graphics-plplot/releases/tag/0.74).
