### ISSUE TITLE
PDL::Graphics::PLplot build doesn't bail out when plplot library cannot be found

### ISSUE THREAD

**Issue by sisyphus** [PDLPorters/pdl-graphics-plplot#9]
Hi,
I struck this when building PDL-Graphics-PLplot-0.74 on Ubuntu-18.04, perl-5.32.0.
(See https://www.perlmonks.org/?node_id=11120908 for the full story.)
I had installed latest PDL, but the plplot library was not present anywhere on the system:

\###############################
$ cpanm -i PDL::Graphics::PLplot
 --> Working on PDL::Graphics::PLplot
Fetching http://www.cpan.org/authors/id/D/DH/DHUNT/PDL-Graphics-PLplot-0.74.tar.gz ... OK
Configuring PDL-Graphics-PLplot-0.74 ... OK
Building and testing PDL-Graphics-PLplot-0.74 ... OK
Successfully installed PDL-Graphics-PLplot-0.74 1 distribution installed
\###############################

Of course, given that there was no plplot library to be found, the module was not built or installed, and most of that output is simply untrue.
It became a little clearer when I switched to using the more verbose cpan utility:

\###############################
$ cpan -i PDL::Graphics::PLplot
[... skip irrelevant preamble ...]
Configuring D/DH/DHUNT/PDL-Graphics-PLplot-0.74.tar.gz with Makefile.PL
PDL is installed

Checking PDL::Graphics::PLplot...
Searching for libplplot.so library.
Searching for libplplotd.so library.
Cannot find plplot library (libplplotd.so), skipping PDL::Graphics::PLplot

      Not building PDL::Graphics::PLplot

Cannot find plplot library (libplplotd.so), skipping PDL::Graphics::PLplot

      Not building PDL::Graphics::PLplot

Checking if your kit is complete...
Looks good
  DHUNT/PDL-Graphics-PLplot-0.74.tar.gz
  /home/sisyphus/perl-5.32.0-d/bin/perl Makefile.PL -- OK
Running make for D/DH/DHUNT/PDL-Graphics-PLplot-0.74.tar.gz
Could not read metadata file. Falling back to other methods to determine prerequisites
make: Nothing to be done for 'all'.
  DHUNT/PDL-Graphics-PLplot-0.74.tar.gz
  /usr/bin/make -- OK
[ ... skip request to install CPAN::DistnameInfo ...]
make: Nothing to be done for 'test'.
  DHUNT/PDL-Graphics-PLplot-0.74.tar.gz
  /usr/bin/make test -- OK
Running make install for DHUNT/PDL-Graphics-PLplot-0.74.tar.gz
make: Nothing to be done for 'install'.
  DHUNT/PDL-Graphics-PLplot-0.74.tar.gz
  /usr/bin/make install  -- OK
\###############################

I would expect that the process should teminate as soon as the decision to not build the module was made.
To instead continue on with untrue assertions is confusing and misleading.

I would actually be inclined to run no checks at all during the Makefile.PL step, and just let the build take its course.
When the plplot library is absent, that would result in the plplot header files not being found during the 'make' step, which is reported as "UNKNOWN" by cpan-testers.

OTOH, if you're then unlucky enough to hit a cpan-tester system where the header files are locatable, but the .so file is not, then the report will be FAIL. 
Chris "Bingos" Williams recently unleashed a smoker that finds the gmp and mpfr headers but fails to find the respective .so files - so I know from first hand experience that this can happen, and that it does result in FAIL, as happens with my gmp and mpfr modules on that smoker. 
(Just thought that, for balance.  I'd mention that downside associated with *not* checking for the availability of the library during the Makefile.PL step.)

Cheers,
Rob

**Comment by mohawk2** [comment]
Thanks! This was a hangover from when P:G:PLplot was part of PDL, and needed to make a dummy Makefile when there was no PLplot installed.
